Update regelung.py
Fellersen/Reglungstechnik pull request #1
Opened 2020-09-17 22:47 UTC by Fellersen

2020-09-17 22:48 UTC, LostInDarkMath requested changes
Looks terrible :(

2020-09-17 22:50 UTC, rathaustreppe reviewed
gurl gurl

2020-09-18 18:00 UTC, LostInDarkMath requested changes
Zum Commit acf7be1af9c67e8a62fe8d5406c705b70b7492fd (plot (PT2)):
- Die Datei `PT2_s_01.txt` würde ich nicht in den `src` Ordner packen. Eher in einen separaten `data`-Ordner oder so.
- Die Leerzeile zwischen den `import`-Statements finde ich verwirrend, weil es alles drei Third-Party-Librarys sind.
- Die `plot`-Funktion hat kein `@pedantic`.
- Das `return 0` in Zeile 18 sollte raus.
- Die Bezeichner `plot`, `t1` und `t2` in Zeile 11 würde ich anders benennen. Nutze Namen, die genau ausdrücken, was das ist.

Das wären so paar Gedanken von mir ;)

2020-09-18 22:07 UTC, merged

2020-09-19 09:47 UTC, LostInDarkMath reviewed
Noch an paar Anmerkungen von mir :)

2020-09-19 09:47 UTC, LostInDarkMath commented on src/regelung.py
> +import numpy
Das `import numpy` doppelt sich mit `import numpy as np`. Also das würde ich entfernen.

2020-09-19 09:47 UTC, LostInDarkMath commented on src/regelung.py
> +def plot_graph(time: numpy.ndarray, value: numpy.ndarray) -> None:
Hier fehlt immer noch das `@pedantic` und statt `numpy.ndarray` schreibst du `np.ndarray`, weil du ja numpy den Alias `np` gegeben hat.

2020-09-19 09:47 UTC, LostInDarkMath commented on src/regelung.py
> +    source_path = 'C:\\Users\\Fellersen\\Documents\\GitHub\\Reglungstechnik\\data\\transmission_characteristics' \
Nutze relative Pfade statt absolute Pfade. Das macht es deinen Nutzern einfacher, den Code auszuführen und versteckt auch deine private Ordnerstruktur auf dem PC.

2020-09-19 09:47 UTC, LostInDarkMath commented on src/regelung.py
> +    time_sys = np.loadtxt(source_path, usecols=0)
Was bedeutet `sys`? Was willst du damit sagen?